@startuml

title Activity Diagram (sortListByCategoryRec())

start

:Software takes category;
note right: the method receives the name of the category from the user_input

:Software check in record_category_name;

if (Is user_input exists?) then (yes)
while(record_category_name->object->next == NULL)
note right: if yes = go to check in if(), if no = return 0, exit from method
  if (user_input == record_category_name->object) then (yes)
    :print object[date, summ, record_name, source];
  else (no)
    :record_category_name->object = record_category_name->object->next;
endif
endwhile 
    :return 0;
else (no)
  :user_input is incorrect!;
  :return 0;
  
endif



stop

@enduml
