@startuml

title Usecase Diagram

left to right direction

actor User

rectangle Software {

    usecase (відстежувати доходи)
    usecase (відстежувати витрати)

   (відстежувати доходи) .> (відстежувати витрати) : include
   User -- (відстежувати доходи)
   User -- (відстежувати витрати)
   
}

@enduml